Repository itsmeow/betteranimalsplus, pull requests merged in 2019-11, with the labels that each got.

#111 Fix campfire recipe .json
  src/main/resources/data/betteranimalsplus/recipes/campfire/crab_campfire.json
  src/main/resources/data/betteranimalsplus/recipes/campfire/pheasant_campfire.json
  src/main/resources/data/betteranimalsplus/recipes/campfire/venison_campfire.json
Labels: confirmed, enhancement, mc:1.14

#113 Add Essential Features Portable Jukebox Crab Rave compatibility
  src/main/java/its_meow/betteranimalsplus/common/CommonEventHandler.java
  src/main/resources/data/minecraft/tags/items/music_discs.json
Labels: enhancement, mc:1.14, mod compat

#114 Add waterlogging support
  src/main/java/its_meow/betteranimalsplus/common/block/BlockAnimalSkull.java
  src/main/java/its_meow/betteranimalsplus/common/block/BlockHandOfFate.java
Labels: confirmed, enhancement, mc:1.14

#115 Add tag support to taming item config and fix taming item config.
  src/main/java/its_meow/betteranimalsplus/common/entity/EntityTameableBetterAnimalsPlus.java
  src/main/java/its_meow/betteranimalsplus/util/EntityTypeContainerTameable.java
Labels: confirmed, enhancement, mc:1.14

#116 Add oredict support to taming item config
  src/main/java/its_meow/betteranimalsplus/common/entity/EntityTameableBetterAnimalsPlus.java
Labels: confirmed, enhancement, mc:1.12

#117 Start of Thaumcraft 6 compat
  build.gradle
  src/main/java/its_meow/betteranimalsplus/BetterAnimalsPlusMod.java
  src/main/java/its_meow/betteranimalsplus/init/ModOreDictSmelting.java
  src/main/java/its_meow/betteranimalsplus/integration/ThaumcraftIntegration.java
Labels: confirmed, enhancement, mc:1.12, mod compat

#118 Update ru_ru.lang
  src/main/resources/assets/betteranimalsplus/lang/ru_ru.lang
Labels: confirmed, enhancement, lang/translation, mc:1.12

#119 Update de_de.json
  src/main/resources/assets/betteranimalsplus/lang/de_de.json
Labels: confirmed, enhancement, lang/translation, mc:1.14
